routes/web.php
<?php

use App\Helpers\EndPoints;
use App\Helpers\Security;
use Illuminate\Support\Facades\Redirect;

Route::get('/users/auth/{key}',
    [
        'uses' => 'UserController@authenticate',
        'as' => 'users.auth'
    ]);

/*
* This loads the home page
* */
//Route::get('/', function () {
//    return Redirect::to(EndPoints::$USER_MANAGEMENT_LOGOUT_LINK);
//})->name('login');

Route::get('/', 'UserController@home')->name('login');


/*
 * Only accessible once logged in
 * */
Route::group(['middleware' => ['web', 'users.authorized' /*'auth'*/]], function () {


//view email attachment
    Route::get('/lms-attachment-link/{letterCategory?}/{letterId?}', "IncomingAndOutgoingLetterController@viewAttachmentSentViaEmail")->name('attachments.email-link');

    /*
     * Test PDF View
     * */
    Route::get('/pdf-view', function () {

        $data = array(
            'menu_selected'=>'reception',
            'level'=> \App\Helpers\AppConstants::$ROLE_CODE_SUPER_USER,
        );

        return view('test/test')->with($data);
    })->name('pdf-view');


    Route::get('/user/logout',
        [
            'uses' => 'UserController@logoutUser',
            'as' => 'logout_user'
        ]);

    Route::get('/letter-movement','LetterMovementController@index')->name('letter_movement');
    Route::get('/memo-movement','LetterMovementController@indexInternalMemo')->name('letter_movement.memo');

    Route::prefix('letter-movement')->group(function(){
//        Route::get('/create/{letter}', 'LetterMovementController@create')->name('letter-movement.create');
        Route::get('/launch/{documentType}/{documentId}', 'LetterMovementController@launch')->name('letter-movement.launch');
        Route::get('/incoming-letter/view/{letter}/{menu}', 'LetterMovementController@viewLetterMovement')->name('letter-movement.view-movement');
        Route::get('/internal-memo/view/{memo}/{menu}', 'LetterMovementController@viewInternalMemoMovement')->name('memo-movement.view-movement');
        Route::get('/forward/{documentType}/{documentId}', 'LetterMovementController@forward')->name('letter-movement.forward');
        Route::get('/return-letter-movement/{documentId}/{returnTo}/{documentType}', 'LetterMovementController@returnIncomingLetter')->name('letter-movement.return');
        Route::get('/list/letter', 'LetterMovementController@letterMovementList')->name('letter-movement.list');
        Route::get('/list/memo', 'LetterMovementController@memoMovementList')->name('letter-movement.list.memo');
    });



    Route::get('/download-link-memo/{internalMemo}', "InternalMemoController@getInternalMemoDownloadLink")->name('download-link-memo');
    Route::get('/download-link-incoming-letter/{letter}', "IncomingLetterController@getLetterDownloadLink")->name('download-link-incoming');
    Route::get('/download-link-outgoing-letter/{outgoingLetter}', "OutgoingLetterController@getLetterDownloadLink")->name('download-link-outgoing');
    Route::get('/download-link-outgoing-letter/receipt/{outgoingLetter}', "OutgoingLetterController@getLetterReceiptDownloadLink")->name('download-link-outgoing.receipt');
    Route::get('/delete-temp-incoming-letter-doc/{documentName}', "IncomingLetterController@deleteTempDocument")->name('delete-temp-incoming-letter-doc');
    Route::get('/delete-temp-outgoing-letter-doc/{documentName}', "OutgoingLetterController@deleteTempDocument")->name('delete-temp-outgoing-letter-doc');

    Route::post('/store', 'ActionController@store')->name('store');
    Route::get('/delete/{table}/{id}', 'ActionController@delete')->name('delete');
    Route::get('/upload', 'FileUploadController@action')->name('upload');

    Route::get('/reception','ReceptionController@index')->name('home')->middleware('users.reception');
    Route::get('/registry','RegistryController@index')->name('registry')->middleware('users.registry');
    Route::get('/ed_office','EdController@index')->name('ed_office')->middleware('users.ed');

    Route::prefix('incoming-letter')->group(function(){
        Route::get('/create', 'IncomingLetterController@create')->name('letter.create');
        Route::get('/edit/{letter}', 'IncomingLetterController@edit')->name('letter.edit');
        Route::get('/readonly/{letter}', 'IncomingLetterController@readonly')->name('letter.readonly');
        Route::get('/upload/{letter}', 'IncomingLetterController@uploadIncomingLetter')->name('letter.upload');
        Route::get('/rename-attached-doc/{letter}', 'IncomingLetterController@renameAttachedDocumentView')->name('letter.rename-attached-doc.view');
        Route::get('/download/{letter}', 'IncomingLetterController@downloadAttachedIncomingLetter')->name('letter.download');
        Route::get('/remove-attached-upload/{letter}', 'IncomingLetterController@removeAttachedIncomingLetter')->name('letter.remove-attached-upload');
        Route::get('/reception/list', 'IncomingLetterController@reception_list')->name('reception.letters.list');
        Route::get('/registry/list', 'IncomingLetterController@registry_list')->name('registry.letters.list');
        Route::get('/ed/list', 'IncomingLetterController@ed_list')->name('ed.letters.list');
        Route::get('/forward/{letter}/{que}', 'IncomingLetterController@forward')->name('letter.forward');
        Route::get('/associations/{letter}','IncomingLetterController@associations')->name('letter.associations');
        Route::get('/history/view/{activeMenu}', 'IncomingLetterController@historyView')->name('letter.history.view');
        Route::get('/history/list/{activeMenu}', 'IncomingLetterController@historyList')->name('letter.history.list');
    });

    Route::prefix('outgoing-letter')->group(function(){
        Route::get('/','OutgoingLetterController@index')->name('outgoingletters');
        Route::get('/create', 'OutgoingLetterController@create')->name('outgoingletter.create');
        Route::get('/upload/{outgoingLetter}', 'OutgoingLetterController@uploadOutgoingLetter')->name('outgoingletter.upload');
        Route::get('/upload/receipt/{outgoingLetter}', 'OutgoingLetterController@uploadOutgoingLetterReceipt')->name('outgoingletter.upload.receipt');
        Route::get('/rename-attached-doc/{letter}', 'OutgoingLetterController@renameAttachedDocumentView')->name('outgoingletter.rename-attached-doc.view');
        Route::get('/download/{outgoingLetter}', 'OutgoingLetterController@downloadAttachedOutgoingLetter')->name('outgoingletter.download');
        Route::get('/remove-attached-upload/{outgoingLetter}', 'OutgoingLetterController@removeAttachedOutgoingLetter')->name('outgoingletter.remove-attached-upload');
        Route::get('/remove-attached-upload/receipt/{outgoingLetter}', 'OutgoingLetterController@removeAttachedOutgoingLetterReceipt')->name('outgoingletter.remove-attached-upload.receipt');
        Route::get('/edit/{outgoingLetter}', 'OutgoingLetterController@edit')->name('outgoingletter.edit');
        Route::get('/list', 'OutgoingLetterController@list')->name('outgoingletters.list');
        Route::get('/associations/{outgoingLetter}','OutgoingLetterController@associations')->name('outgoingletters.associations');

   });

    Route::prefix('internal-memo')->group(function(){
        Route::get('/create', 'InternalMemoController@create')->name('memo.create');
        Route::get('/edit/{internalMemo}', 'InternalMemoController@edit')->name('memo.edit');
        Route::get('/readonly/{internalMemo}', 'InternalMemoController@readonly')->name('memo.readonly');
        Route::get('/upload/{internalMemo}', 'InternalMemoController@uploadInternalMemo')->name('memo.upload');
        Route::get('/rename-attached-doc/{internalMemo}', 'InternalMemoController@renameAttachedDocumentView')->name('memo.rename-attached-doc.view');
        Route::get('/download/{internalMemo}', 'InternalMemoController@downloadAttachedIncomingLetter')->name('memo.download');
        Route::get('/remove-attached-upload/{internalMemo}', 'InternalMemoController@removeAttachedInternalMemo')->name('memo.remove-attached-upload');
        Route::get('/reception', 'InternalMemoController@receptionIndex')->name('memo.reception.index');
        Route::get('/registry', 'InternalMemoController@registryIndex')->name('memo.registry.index');
        Route::get('/ed', 'InternalMemoController@edOfficeIndex')->name('memo.ed.index');
        Route::get('/reception/list', 'InternalMemoController@receptionList')->name('memo.reception.list');
        Route::get('/registry/list', 'InternalMemoController@registryList')->name('memo.registry.list');
        Route::get('/ed/list', 'InternalMemoController@edOfficeList')->name('memo.ed.list');
        Route::get('/forward/{internalMemo}/{que}', 'InternalMemoController@forward')->name('memo.forward');
    });


    Route::prefix('letters')->group(function(){
        Route::get('/deletion/{letterCategory}/{letterId}', 'IncomingAndOutgoingLetterController@delete')->name('letters.deletion');
    });


    Route::prefix('letter-association')->group(function(){
        Route::get('/list/{letterId}/{letterCategory}', 'LetterAssociationController@associationList')->name('letter-association.list');
        Route::get('/create/{letterId}/{letterCategory}', 'LetterAssociationController@create')->name('letter-association.create');
        Route::get('/letters-incoming/{letter}', 'LetterAssociationController@listIncoming')->name('letter-association.letters-incoming');
        Route::get('/letters-outgoing/{outgoingLetter}', 'LetterAssociationController@listOutgoing')->name('letter-association.letters-outgoing');
    });

    Route::prefix('upload')->group(function(){
        Route::post('/incoming-letter', 'UploadController@uploadIncomingLetter')->name('upload.incoming-letter');
        Route::post('/internal-memo', 'UploadController@uploadInternalMemo')->name('upload.memo');
        Route::post('/outgoing-letter', 'UploadController@uploadOutgoingLetter')->name('upload.outgoing-letter');

app/IncomingLetter.php
<?php

namespace App;

use App\Helpers\AppConstants;
use App\Helpers\Security;
use Illuminate\Database\Eloquent\Model;

class IncomingLetter extends Model
{

    public static function laratablesCustomAction($letter)
    {
        $username = session(Security::$SESSION_USER) != null ? session(Security::$SESSION_USER)->username : '';
        $level = 'reception';

        $data = array(
            'username' => $username,
            'level' => $level,
            'letter' => $letter,
        );

        return view('List_Actions.list_action_new')->with($data)->render();

    }
    public static function laratablesCustomRegistryAction($letter)
    {
        $username = session(Security::$SESSION_USER) != null ? session(Security::$SESSION_USER)->username : '';
        $level = 'registry';
        return view('List_Actions.list_action_new', compact('letter','level','username'))->render();
    }
    public static function laratablesCustomEDAction($letter)
    {
        $username = session(Security::$SESSION_USER) != null ? session(Security::$SESSION_USER)->username : '';
        $level = 'ed';
        return view('List_Actions.list_action_new', compact('letter','level','username'))->render();
    }

    public static function laratablesCustomAssociationAction($letter)
    {
        $level = 'ed';
        return view('List_Actions.list_action_associate_incoming', compact('letter','level'))->render();
    }

    public static function laratablesCustomReadOnlyAction($letter)
    {
        $level = 'ed';
        $data = array(
            'level' => $level,
            'letter' => $letter,
        );
        return view('List_Actions.list_action_readonly_incoming')->with($data)->render();

    }

    public static function laratablesCustomCheckBox($letter)
    {
        $level = 'ed';
        $letterCategory = 'incoming';
        return view('extra_cols.associate_cbx', compact('letter','level','letterCategory'))->render();
    }

    public static function laratablesAdditionalColumns()
    {
        $columns = ['incoming_letter_file_name','incoming_letter_upload_user','from_user_full_name'];
        return $columns;
    }

    public function letterType(){
        return $this->belongsTo('App\LetterType');
    }

    /*public function letterMovements(){
        return $this->hasMany('App\LetterMovement','letter_id','id');
    }*/

    public function letterMovements(){
        return $this->morphMany('App\LetterMovement','moveable');
    }

    public static function laratablesCustomLetterTypeName($letter)
    {
        $type = LetterType::where('id','=', $letter->letter_type_id)->first();
        $data = $type != null ? $type->letter_type_name : '';
        return $data;
    }

    /**
     * Returns truncated name for the datatables.
     *
     * @param \App\User
     * @return string
     */
    public static function laratablesSubject($letter)
    {
        if($letter->letter_category == AppConstants::$LETTER_CATEGORY_INCOMING_LETTER){
            return $letter->subject;
        }else{
            return $letter->subject .' ('.$letter->from_user_full_name.')';
        }
    }

    public function getDateSentAttribute($value){
        return date("M d Y", strtotime($value));
    }

    public function getDateReceivedPpdaAttribute($value){
        return date("M d Y", strtotime($value));
    }

    public function setSubjectAttribute($value){

        $trimmedContent = trim($value);
        $trimmedContent = strtoupper($trimmedContent);
        $trimmedContent = preg_replace('/\s+/', ' ',$trimmedContent);
        $this->attributes['subject'] = $trimmedContent;

    }



}

app/LetterMovement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LetterMovement extends Model
{

    public function moveable(){
        return $this->morphTo();
    }

    public function letter(){
        return $this->belongsTo('App\IncomingLetter','moveable_id','id');
    }

    public function memo(){
        return $this->belongsTo('App\InternalMemo','moveable_id','id');
    }

    public static function laratablesCustomLetterMovtAction($letterMovement)
    {
        $letter = IncomingLetter::find($letterMovement->moveable_id);
        $level = 'ed';
        return view('List_Actions.list_action_letter_movt', compact('letter','level'))->render();
    }

    public static function laratablesCustomMemoMovtAction($letterMovement)
    {
        $memo = InternalMemo::find($letterMovement->moveable_id);
        $level = 'ed';
        return view('List_Actions.list_action_memo_movt', compact('memo','level'))->render();
    }

    public static function laratablesCustomLetterTypeName($letterMovement)
    {

        $letter = IncomingLetter::where('id','=',$letterMovement->moveable_id)->first();

        if($letter == null){
            return '';
        }

        $type = LetterType::where('id','=', $letter->letter_type_id)->first();
        $data = $type != null ? $type->letter_type_name : '';
        return $data;
    }

}

resources/views/letter_movements/index.blade.php
@extends('layouts.app')
@section('title') Letter Movements @endsection
@section('content')
    <div class="page-header">
        <h1>
            Letter Movements
            <small>
                <i class="ace-icon fa fa-angle-double-right"></i>
                List
            </small>
        </h1>
    </div>
    <div class="form-actions no-margin-bottom">
        <div class="float-alert center">
            <div class="float-alert-container">
                <div class="col-md-12">
                    <a href="{{ route('letter_movement.memo') }}" class="clarify btn btn-primary btn-sm" title="View Internal Memo Movements">View Internal Memo Movements</a>
                    <hr>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>
    <table class="data-table letter_movements table table-striped table-bordered table-hover no-margin-bottom no-border-top hide_first_column" >
        <thead>
        <tr>
            <th></th>
            <th style="vertical-align: top;width: 15%">Entity Name</th>
            <th style="vertical-align: top;width: 20%">Subject</th>
            <th style="vertical-align: top">Date Sent</th>
            <th style="vertical-align: top">Date Received PPDA</th>
            <th style="vertical-align: top">Date Received Registry</th>
            <th style="vertical-align: top">Sender Reference No.</th>
            <th style="vertical-align: top">PPDA Reference No.</th>
            <th style="vertical-align: top">Attention To</th>
            <th style="vertical-align: top">Letter Type</th>
            <th style="vertical-align: top">Attached Document</th>
            <th style="vertical-align: top"></th>
        </tr>
        </thead>
    </table>
@endsection

resources/views/letter_movements/view_letter_movement.blade.php
<div class="">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body smaller_accordions">


                    <form action="{{route('store')}}" class="form-horizontal" method="post" id="form_{{time()}}">

                        <input type="hidden" name="ext" value="1">
                        @csrf
                        <input type="hidden" name="table" value="LetterMovement">
                        <input type="hidden" name="r_fld[letter_id]" value="{{ $letter->id }}">

                        <div id="accordion_ad_review"
                             class="accordion-style1 panel-group accordion-style2 management_letter_accordion">
                            <!-- panel 1 -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        @if(isset($letter->incoming_letter_file_name))
                                        <div class="row" style="vertical-align: middle">
                                            <div class="col-md-9"><a class="accordion-toggle" data-parent="#accordion_ad_review" href="#section31_ad_review" aria-expanded="false">Letter Movements</a></div>
                                            <div class="col-md-3"><a href="#!" class="btn btn-danger align-right pdf-link" data-remove-temp-url="{{route('delete-temp-incoming-letter-doc','')}}" data-download-url = "{{route('download-link-incoming',$letter->id)}}" data-pdf-url = "" data-id="{{ $letter->id }}">View Attached Document</a></div>
                                        </div>
                                        @else
                                            <div class="col-md-12"><a class="accordion-toggle" data-parent="#accordion_ad_review" href="#section31_ad_review" aria-expanded="false">Letter Movements</a></div>
                                        @endif
                                    </h4>
                                </div>

                                <div class="panel-collapse " id="section31_ad_review" aria-expanded="false">
                                    <div class="panel-body">

                                        <table class="table table-striped " style="width: 98%; margin: 0 auto">
                                            <tr>
                                                <th>From</th>
                                                <th>From Department</th>
                                                <th>Sent To</th>
                                                <th>To Department</th>
                                                <th>Date Sent</th>
                                                <th>Deadline for Action</th>
                                                <th>Required Action</th>
                                            </tr>
                                            @if(isset($letterMovements) && count($letterMovements) >0)
                                                @foreach($letterMovements as $movt)
                                                    <tr style="height: 70px;">
                                                        <td style="padding-top: 5px">
                                                            {{$movt->from_name}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{$movt->from_department}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{$movt->to_name}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{$movt->to_department}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{date("F d Y", strtotime($movt->date_sent))}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{ date("F d Y", strtotime($movt->deadline_for_action))}}
                                                        </td>
                                                        <td style="padding-top: 5px; width: 35%">
                                                            {{$movt->required_action}}
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            @endif
                                        </table>


                                    </div>
                                </div>
                            </div>

                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-12 offset-md-3 center">
                                @if(isset($isCurrentAssignee) && $isCurrentAssignee && $menu == 'letter-movement')
                                    <a href="{{ route('letter-movement.forward',['incoming_letter',$letter->id]) }}" class="clarify btn btn-primary btn-sm" title="Forward Incoming Letter">Forward Letter</a>
                                    @if(isset($showReturnToSenderBtn) && $showReturnToSenderBtn)
                                    <a href="{{ route('letter-movement.return',[$letter->id,'sender','incoming_letter']) }}" class="clarify_secondary btn btn-danger btn-sm" title="Return Incoming Letter to Sender">Return to Sender</a>
                                    @endif
                                    @if(isset($showReturnToEdBtn) && $showReturnToEdBtn)
                                    <a href="{{ route('letter-movement.return',[$letter->id,'ed','incoming_letter']) }}" class="clarify_secondary btn btn-danger btn-sm" title="Return Incoming Letter to ED's Office">Return to ED's Office</a>
                                    @endif
                                @endif
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

resources/views/letter_movements/view_memo_movement.blade.php
<div class="">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body smaller_accordions">

                    <form action="{{route('store')}}" class="form-horizontal" method="post" id="form_{{time()}}">

                        <input type="hidden" name="ext" value="1">
                        @csrf
                        <input type="hidden" name="table" value="LetterMovement">
                        <input type="hidden" name="r_fld[letter_id]" value="{{ $memo->id }}">

                        <div id="accordion_ad_review"
                             class="accordion-style1 panel-group accordion-style2 management_letter_accordion">
                            <!-- panel 1 -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        @if(isset($memo->memo_file_name))
                                        <div class="row" style="vertical-align: middle">
                                            <div class="col-md-9"><a class="accordion-toggle" data-parent="#accordion_ad_review" href="#section31_ad_review" aria-expanded="false">Internal Memo Movements</a></div>
                                            <div class="col-md-3"><a href="#!" class="btn btn-danger align-right pdf-link" data-remove-temp-url="{{route('delete-temp-incoming-letter-doc','')}}" data-download-url = "{{route('download-link-memo',$memo->id)}}" data-pdf-url = "" data-id="{{ $memo->id }}">View Attached Document</a></div>
                                        </div>
                                        @else
                                            <div class="col-md-12"><a class="accordion-toggle" data-parent="#accordion_ad_review" href="#section31_ad_review" aria-expanded="false">Internal Memo Movements</a></div>
                                        @endif
                                    </h4>
                                </div>

                                <div class="panel-collapse " id="section31_ad_review" aria-expanded="false">
                                    <div class="panel-body">

                                        <table class="table table-striped " style="width: 98%; margin: 0 auto">
                                            <tr>
                                                <th>From</th>
                                                <th>From Department</th>
                                                <th>Sent To</th>
                                                <th>To Department</th>
                                                <th>Date Sent</th>
                                                <th>Deadline for Action</th>
                                                <th>Required Action</th>
                                            </tr>
                                            @if(isset($memoMovements) && count($memoMovements) >0)
                                                @foreach($memoMovements as $movt)
                                                    <tr style="height: 70px;">
                                                        <td style="padding-top: 5px">
                                                            {{$movt->from_name}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{$movt->from_department}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{$movt->to_name}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{$movt->to_department}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{date("F d Y", strtotime($movt->date_sent))}}
                                                        </td>
                                                        <td style="padding-top: 5px">
                                                            {{ date("F d Y", strtotime($movt->deadline_for_action))}}
                                                        </td>
                                                        <td style="padding-top: 5px; width: 35%">
                                                            {{$movt->required_action}}
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            @endif
                                        </table>


                                    </div>
                                </div>
                            </div>

                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-12 offset-md-3 center">
                                @if(isset($isCurrentAssignee) && $isCurrentAssignee && $menu == 'letter-movement')
                                    <a href="{{ route('letter-movement.forward',['internal_memo',$memo->id]) }}" class="clarify_tertiary btn btn-primary btn-sm" title="Forward Internal Memo">Forward Memo</a>
                                    @if(isset($showReturnToSenderBtn) && $showReturnToSenderBtn)
                                    <a href="{{ route('letter-movement.return',[$memo->id,'sender','internal_memo']) }}" class="clarify_tertiary btn btn-danger btn-sm" title="Return Internal Memo to Sender">Return to Sender</a>
                                    @endif
                                    @if(isset($showReturnToEdBtn) && $showReturnToEdBtn)
                                    <a href="{{ route('letter-movement.return',[$memo->id,'ed','internal_memo']) }}" class="clarify_tertiary btn btn-danger btn-sm" title="Return Internal Memo to ED's Office">Return to ED's Office</a>
                                    @endif
                                @endif
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>